#dataset configs
dataset: RegDB
trial: 1
train_boost: False
test_boost: False

mode_1: ir2rgb
test_mode_1 : [2, 1]
mode_2: rgb2ir
test_mode_2 : [1, 2]
eval_iter: 1

train_batch_size: 20
train_num_instances: 5

bg_knn: 50

#gnn
gnn_k1_cross: 18
gnn_k2_cross: 3

# jkd d configs
k1: 10
k2: 6

#path
base_dir: ../save/RegDB/
data_dir: ../dataset/RegDB/
extend_dir: 144x288/1/