stage: 2

#train configs
num_iter: 150
max_epoch: 90
use_id_loss: True

#train
resume_path: BASE_CAM/checkpoints/stage1/train_2_epoch_50.pth

#path
logs_dir: /logs/stage2/
model_dir: /checkpoints/stage2
