#dataset configs
dataset: LLCM

mode_1: ir2rgb
test_mode_1 : [2, 1]
mode_2: rgb2ir
test_mode_2 : [1, 2]
eval_iter: 1

train_batch_size: 80
train_num_instances: 10
num_iter: 200
bg_knn: 125
smooth_weight: 0.5
#gnn
gnn_k1_cross: 15
gnn_k2_cross: 3
# jkd d configs
k1: 25
k2: 6

#path
base_dir: ../save/LLCM/
data_dir: ../dataset/LLCM/
extend_dir: 144x288/