# valid config
eval_iter: 10

# reranking
reranking_type: GCR
gnn_k1: 19
gnn_k2: 5
la: 0.7

# pre train
resume_path: val/checkpoints/stage2/best_epoch_72.pth

# path
logs_dir: /logs/test/
