#dataset configs
dataset: SYSU

mode_1: all
test_mode_1 : [2, 1]
mode_2: indoor
test_mode_2 : [2, 1]
eval_iter: 10

train_batch_size: 40
train_num_instances: 10
num_iter: 300
bg_knn: 50
smooth_weight: 0.5
#gnn
gnn_k1_cross: 15
gnn_k2_cross: 3
# jkd d configs
k1: 30
k2: 6

#path
base_dir: ../save/SYSU/
data_dir: ../dataset/SYSU-MM01/
extend_dir: 144x288/