# valid config
eval_iter: 10

# reranking
reranking_type: GCR
gnn_k1: 28
gnn_k2: 7
la: 0.5

# pre train
resume_path: BEST/checkpoints/stage2/best_epoch_69.pth

# path
logs_dir: /logs/test/
